### ISSUE TITLE
Falta URL módulo HTTP Request(GET)

### ISSUE THREAD

**Issue by zerocoolspain** [ferrancc4/Telegram-Bot-Node-Red-Sync-Teslamate-ABRP#1]
Al ejecutarlo me da un error porque falta una URL en el módulo HTTP Request(GET). Está en la parte de geoapify.

**Comment by ferrancc4** [comment]
Te has dado de alta y obtenido el token de geoapy? He revisado y deveria funcionar

**Comment by ferrancc4** [comment]
Ya està resuelto puedes volver a descargar el flow y deveria estar solucionado

**Comment by zerocoolspain** [comment]
Ahora ya no da el error. Thanks! :-)
